server:
  port: 9000
  servlet:
    context-path: /talus
spring:
  application:
    name: talus-application

management:
  endpoints:
    web:
      base-path: /metrics
      exposure:
        include: '*'
    jmx:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
    metrics:
      enabled: true
  metrics:
    export:
      prometheus:
        descriptions: true
        enabled: true


myProps:
  corePoolSize: 50
  maxPoolSize: 100
  queueCapacity: 50
